config/routes.rb
MiniApp::Application.routes.draw do

  namespace :admin do
    resources :products
    resources :orders
  end

end

app/models/order.rb
class Order

  include ::Mongoid::Document
  include ::Mongoid::Timestamps

  ## fields ##
  field :total, :type => Float
  field :notes

  ## associations ##
  referenced_in :site

  ## validations ##
  validates_presence_of       :total
  validates_numericality_of   :total

end

app/models/product.rb
class Product

  include ::Mongoid::Document
  include ::Mongoid::Timestamps

  ## fields ##
  field :name
  field :price, :type => Float
  field :description

  ## associations ##
  referenced_in :site

  ## validations ##
  validates_presence_of       :name, :price
  validates_numericality_of   :price

  ## scopes ##
  scope :ordered, :order_by => :name.asc

  ## behaviors ##
  mount_uploader :image, ShopUploader

  ## methods ##

  def to_liquid
    Shop::Liquid::Drops::Product.new(self)
  end

end

app/models/site.rb
class Site

  ## associations ##
  references_many :products,  :validate => false
  references_many :orders,    :validate => false

end

app/controllers/admin/orders_controller.rb
module Admin

  class OrdersController < BaseController

    respond_to :html

    sections 'products'

  end

end

app/controllers/admin/products_controller.rb
module Admin

  class ProductsController < BaseController

    respond_to :html

    sections 'products'

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/orders/index.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

%p!= t('.help')

- if @orders.empty?
  %p.no-items!= t('.no_items')
- else
  %ul{ :id => 'orders-list', :class => "list" }
    - @orders.each do |order|
      %li
        %em
        %strong
          = order.total
        .more
          %span
            != t('admin.contents.index.created_at')
          = l order.created, :format => :short rescue 'n/a'

app/views/admin/products/_form.html.haml
= f.foldable_inputs :name => :information, :class => 'off' do

  = f.input :name
  = f.input :price
  = f.input :description, :as => 'text'

  = f.custom_input :image, :css => 'file' do
    = f.file_field :image
    - if f.object.image?
      %p.remove
        %strong
          = link_to File.basename(f.object.image.url), f.object.image.url
        %span
          &nbsp;/&nbsp;
          != t('.delete_file')
          = f.check_box :remove_image

app/views/admin/products/edit.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

= semantic_form_for @product, :url => admin_product_url(@product), :html => { :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_products_url, :button_label => :update

app/views/admin/products/index.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

- if @products.empty?
  %p.no-items!= t('.no_items', :url => new_admin_product_url)
- else
  %ul{ :id => 'products-list', :class => "list" }
    - @products.each do |product|
      %li
        %em
        %strong
          = link_to product.name, edit_admin_product_url(product)
        .more
          %span
            != t('admin.contents.index.updated_at')
          = l product.updated_at, :format => :short rescue 'n/a'

          = link_to image_tag('admin/list/icons/trash.png', :alt => t('admin.buttons.delete')), admin_product_url(product), :class => 'remove', :confirm => t('admin.messages.confirm'), :method => :delete

app/views/admin/products/new.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

= semantic_form_for @product, :url => admin_products_url, :html => { :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_products_url, :button_label => :create

app/views/admin/shared/actions/_products.html.haml
= link_to content_tag(:em) + content_tag(:span, t('admin.products.index.new')), new_admin_product_url

app/views/layouts/admin/orders/index.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

%p!= t('.help')

- if @orders.empty?
  %p.no-items!= t('.no_items')
- else
  %ul{ :id => 'orders-list', :class => "list" }
    - @orders.each do |order|
      %li
        %em
        %strong
          = order.total
        .more
          %span
            != t('admin.contents.index.created_at')
          = l order.created, :format => :short rescue 'n/a'

app/views/layouts/admin/products/_form.html.haml
= f.foldable_inputs :name => :information, :class => 'off' do

  = f.input :name
  = f.input :price
  = f.input :description, :as => 'text'

  = f.custom_input :image, :css => 'file' do
    = f.file_field :image
    - if f.object.image?
      %p.remove
        %strong
          = link_to File.basename(f.object.image.url), f.object.image.url
        %span
          &nbsp;/&nbsp;
          != t('.delete_file')
          = f.check_box :remove_image

app/views/layouts/admin/products/edit.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

= semantic_form_for @product, :url => admin_product_url(@product), :html => { :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_products_url, :button_label => :update

app/views/layouts/admin/products/index.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

- if @products.empty?
  %p.no-items!= t('.no_items', :url => new_admin_product_url)
- else
  %ul{ :id => 'products-list', :class => "list" }
    - @products.each do |product|
      %li
        %em
        %strong
          = link_to product.name, edit_admin_product_url(product)
        .more
          %span
            != t('admin.contents.index.updated_at')
          = l product.updated_at, :format => :short rescue 'n/a'

          = link_to image_tag('admin/list/icons/trash.png', :alt => t('admin.buttons.delete')), admin_product_url(product), :class => 'remove', :confirm => t('admin.messages.confirm'), :method => :delete

app/views/layouts/admin/products/new.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/shop_menu', :show

- content_for :actions do
  = render 'admin/shared/actions/products'

%p!= t('.help')

= semantic_form_for @product, :url => admin_products_url, :html => { :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_products_url, :button_label => :create

app/views/layouts/admin/shared/actions/_products.html.haml
= link_to content_tag(:em) + content_tag(:span, t('admin.products.index.new')), new_admin_product_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>